version: '3.8'
services:
  spring-boot-hibernate-hazelcast-cache-example:
    image: suayb/spring-boot-hibernate-hazelcast-cache-example:latest
    container_name: spring-boot-hibernate-hazelcast-cache-example
    restart: ${RESTART_POLICY}
    networks:
      - back-tier
    depends_on:
      - postgresql
    environment:
      - TZ
      - _JAVA_OPTIONS
      - SPRING_PROFILES_ACTIVE
      - SPRING_DATASOURCE_URL
      - SPRING_DATASOURCE_USERNAME
      - SPRING_DATASOURCE_PASSWORD
      - CACHE_HAZELCAST_TIME_TO_LIVE_SECONDS
      - CACHE_HAZELCAST_BACKUP_COUNT
    ports:
      - 9090:9090

  postgresql:
    image: bitnami/postgresql:13
    container_name: postgresql
    restart: ${RESTART_POLICY}
    networks:
      - back-tier
    environment:
      - TZ
      - POSTGRESQL_LOG_TIMEZONE
      - POSTGRESQL_USERNAME
      - POSTGRESQL_PASSWORD
      - POSTGRESQL_DATABASE
      - POSTGRESQL_POSTGRES_PASSWORD
    volumes:
      - postgresql_data:/bitnami/postgresql
    ports:
      - 5432:5432

networks:
  back-tier:
    driver: bridge
    name: back-tier

volumes:
  postgresql_data:
    driver: local
    name: postgresql_data
